# Basic
title: Hexo
subtitle: Fastest blogging framework
description: 
url: http://yoursite.com
author: John Doe
email:

# Permalink
permalink: :year/:month/:day/:title
tag_dir: tags
archive_dir: archives
category: posts

# Server
port: 4000

# Date / Time format
# Hexo uses Moment.js to parse and display date
# Reference: http://momentjs.com/docs/#/displaying/format/
date_format: MMM D, YYYY
time_format: H:mm:ss

# Pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname:

# Extensions
plugins: []
theme: light