# Basic
title: Zespia
subtitle: 
description: 
url: http://zespia.tw
author: SkyArrow
email: tommy351@gmail.com

# Permalink
permalink: :year/:month/:day/:title
tag_dir: tags
archive_dir: archives
category: posts

# Server
port: 4000

# Date / Time format
# Hexo uses Moment.js to parse and display date
# Reference: http://momentjs.com/docs/#/displaying/format/
date_format: YYYY/M/D
time_format: H:mm:ss

# Pagination
per_page: 5
pagination_dir: page
excerpt_link: Read More

# Disqus
disqus_shortname: zespiatw

# Extensions
plugins: []
theme: slash